language: haskell
before_install:
  - sudo apt-add-repository ppa:openrave/release
  - sudo apt-get update
  - sudo apt-get install assimp
install:
  - cabal update
  - cabal install
notifications:
  email:
    on_success: change
    on_failure: always
